/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  activity: () => import("@/views/activity/index.vue"),
  agent_report: () => import("@/views/agent/report/index.vue"),
  agent_role: () => import("@/views/agent/role/index.vue"),
  agent_user: () => import("@/views/agent/user/index.vue"),
  content_about: () => import("@/views/content/about/index.vue"),
  content_marquee: () => import("@/views/content/marquee/index.vue"),
  content_message: () => import("@/views/content/message/index.vue"),
  content_news: () => import("@/views/content/news/index.vue"),
  content_popup: () => import("@/views/content/popup/index.vue"),
  "finance_recharge-audit": () => import("@/views/finance/recharge-audit/index.vue"),
  "finance_recharge-history": () => import("@/views/finance/recharge-history/index.vue"),
  "finance_spin-record": () => import("@/views/finance/spin-record/index.vue"),
  "finance_transaction-log": () => import("@/views/finance/transaction-log/index.vue"),
  "finance_withdraw-audit": () => import("@/views/finance/withdraw-audit/index.vue"),
  "finance_withdraw-history": () => import("@/views/finance/withdraw-history/index.vue"),
  home: () => import("@/views/home/index.vue"),
  mall_category: () => import("@/views/mall/category/index.vue"),
  mall_goods: () => import("@/views/mall/goods/index.vue"),
  mall_shipping: () => import("@/views/mall/shipping/index.vue"),
  "project_balance-order": () => import("@/views/project/balance-order/index.vue"),
  project_balance: () => import("@/views/project/balance/index.vue"),
  project_category: () => import("@/views/project/category/index.vue"),
  project_guarantor: () => import("@/views/project/guarantor/index.vue"),
  project_list: () => import("@/views/project/list/index.vue"),
  project_order: () => import("@/views/project/order/index.vue"),
  "quick-process": () => import("@/views/quick-process/index.vue"),
  "system_admin-user": () => import("@/views/system/admin-user/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_log: () => import("@/views/system/log/index.vue"),
  system_permission: () => import("@/views/system/permission/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  "user_checkin-log": () => import("@/views/user/checkin-log/index.vue"),
  user_checkin: () => import("@/views/user/checkin/index.vue"),
  user_kyc: () => import("@/views/user/kyc/index.vue"),
  user_level: () => import("@/views/user/level/index.vue"),
  "user_login-log": () => import("@/views/user/login-log/index.vue"),
  user_member: () => import("@/views/user/member/index.vue"),
  user_online: () => import("@/views/user/online/index.vue"),
  user_relation: () => import("@/views/user/relation/index.vue"),
  user_wallet: () => import("@/views/user/wallet/index.vue"),
};
