/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'activity',
    path: '/activity',
    component: 'layout.base$view.activity',
    meta: {
      title: 'activity',
      i18nKey: 'route.activity',
      icon: 'ph:confetti',
      order: 30,
      permissions: ['activity.view']
    }
  },
  {
    name: 'agent',
    path: '/agent',
    component: 'layout.base',
    meta: {
      title: 'agent',
      i18nKey: 'route.agent',
      icon: 'ph:identification-badge',
      order: 50
    },
    children: [
      {
        name: 'agent_report',
        path: '/agent/report',
        component: 'view.agent_report',
        meta: {
          title: 'agent_report',
          i18nKey: 'route.agent_report',
          icon: 'ph:chart-pie-slice',
          permissions: ['agent.report.view']
        }
      },
      {
        name: 'agent_role',
        path: '/agent/role',
        component: 'view.agent_role',
        meta: {
          title: 'agent_role',
          i18nKey: 'route.agent_role',
          icon: 'ph:crown',
          permissions: ['agent.role.view']
        }
      },
      {
        name: 'agent_user',
        path: '/agent/user',
        component: 'view.agent_user',
        meta: {
          title: 'agent_user',
          i18nKey: 'route.agent_user',
          icon: 'ph:user-switch',
          permissions: ['agent.user.view']
        }
      }
    ]
  },
  {
    name: 'content',
    path: '/content',
    component: 'layout.base',
    meta: {
      title: 'content',
      i18nKey: 'route.content',
      icon: 'ph:newspaper',
      order: 90
    },
    children: [
      {
        name: 'content_about',
        path: '/content/about',
        component: 'view.content_about',
        meta: {
          title: 'content_about',
          i18nKey: 'route.content_about',
          icon: 'ph:info',
          permissions: ['content.about.view']
        }
      },
      {
        name: 'content_marquee',
        path: '/content/marquee',
        component: 'view.content_marquee',
        meta: {
          title: 'content_marquee',
          i18nKey: 'route.content_marquee',
          icon: 'ph:text-align-left',
          permissions: ['content.marquee.view']
        }
      },
      {
        name: 'content_message',
        path: '/content/message',
        component: 'view.content_message',
        meta: {
          title: 'content_message',
          i18nKey: 'route.content_message',
          icon: 'ph:envelope-simple',
          permissions: ['content.message.view']
        }
      },
      {
        name: 'content_news',
        path: '/content/news',
        component: 'view.content_news',
        meta: {
          title: 'content_news',
          i18nKey: 'route.content_news',
          icon: 'ph:article',
          permissions: ['content.news.view']
        }
      },
      {
        name: 'content_popup',
        path: '/content/popup',
        component: 'view.content_popup',
        meta: {
          title: 'content_popup',
          i18nKey: 'route.content_popup',
          icon: 'ph:browser',
          permissions: ['content.popup.view']
        }
      }
    ]
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance',
      icon: 'ph:currency-circle-dollar',
      order: 60
    },
    children: [
      {
        name: 'finance_recharge-audit',
        path: '/finance/recharge-audit',
        component: 'view.finance_recharge-audit',
        meta: {
          title: 'finance_recharge-audit',
          i18nKey: 'route.finance_recharge-audit',
          icon: 'ph:check-circle',
          permissions: ['finance.recharge-audit.view']
        }
      },
      {
        name: 'finance_recharge-history',
        path: '/finance/recharge-history',
        component: 'view.finance_recharge-history',
        meta: {
          title: 'finance_recharge-history',
          i18nKey: 'route.finance_recharge-history',
          icon: 'ph:clock-clockwise',
          permissions: ['finance.recharge-history.view']
        }
      },
      {
        name: 'finance_spin-record',
        path: '/finance/spin-record',
        component: 'view.finance_spin-record',
        meta: {
          title: 'finance_spin-record',
          i18nKey: 'route.finance_spin-record',
          icon: 'ph:circle-notch',
          permissions: ['finance.spin-record.view']
        }
      },
      {
        name: 'finance_transaction-log',
        path: '/finance/transaction-log',
        component: 'view.finance_transaction-log',
        meta: {
          title: 'finance_transaction-log',
          i18nKey: 'route.finance_transaction-log',
          icon: 'ph:scroll',
          permissions: ['finance.transaction-log.view']
        }
      },
      {
        name: 'finance_withdraw-audit',
        path: '/finance/withdraw-audit',
        component: 'view.finance_withdraw-audit',
        meta: {
          title: 'finance_withdraw-audit',
          i18nKey: 'route.finance_withdraw-audit',
          icon: 'ph:seal-check',
          permissions: ['finance.withdraw-audit.view']
        }
      },
      {
        name: 'finance_withdraw-history',
        path: '/finance/withdraw-history',
        component: 'view.finance_withdraw-history',
        meta: {
          title: 'finance_withdraw-history',
          i18nKey: 'route.finance_withdraw-history',
          icon: 'ph:clock-counter-clockwise',
          permissions: ['finance.withdraw-history.view']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 10
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'mall',
    path: '/mall',
    component: 'layout.base',
    meta: {
      title: 'mall',
      i18nKey: 'route.mall',
      icon: 'ph:storefront',
      order: 80
    },
    children: [
      {
        name: 'mall_category',
        path: '/mall/category',
        component: 'view.mall_category',
        meta: {
          title: 'mall_category',
          i18nKey: 'route.mall_category',
          icon: 'ph:folders',
          permissions: ['mall.category.view']
        }
      },
      {
        name: 'mall_goods',
        path: '/mall/goods',
        component: 'view.mall_goods',
        meta: {
          title: 'mall_goods',
          i18nKey: 'route.mall_goods',
          icon: 'ph:package',
          permissions: ['mall.goods.view']
        }
      },
      {
        name: 'mall_shipping',
        path: '/mall/shipping',
        component: 'view.mall_shipping',
        meta: {
          title: 'mall_shipping',
          i18nKey: 'route.mall_shipping',
          icon: 'ph:truck',
          permissions: ['mall.shipping.view']
        }
      }
    ]
  },
  {
    name: 'project',
    path: '/project',
    component: 'layout.base',
    meta: {
      title: 'project',
      i18nKey: 'route.project',
      icon: 'ph:briefcase',
      order: 70
    },
    children: [
      {
        name: 'project_balance',
        path: '/project/balance',
        component: 'view.project_balance',
        meta: {
          title: 'project_balance',
          i18nKey: 'route.project_balance',
          icon: 'ph:piggy-bank',
          permissions: ['project.balance.view']
        }
      },
      {
        name: 'project_balance-order',
        path: '/project/balance-order',
        component: 'view.project_balance-order',
        meta: {
          title: 'project_balance-order',
          i18nKey: 'route.project_balance-order',
          icon: 'ph:scroll',
          permissions: ['project.balance-order.view']
        }
      },
      {
        name: 'project_category',
        path: '/project/category',
        component: 'view.project_category',
        meta: {
          title: 'project_category',
          i18nKey: 'route.project_category',
          icon: 'ph:folders',
          permissions: ['project.category.view']
        }
      },
      {
        name: 'project_guarantor',
        path: '/project/guarantor',
        component: 'view.project_guarantor',
        meta: {
          title: 'project_guarantor',
          i18nKey: 'route.project_guarantor',
          icon: 'ph:shield-check',
          permissions: ['project.guarantor.view']
        }
      },
      {
        name: 'project_list',
        path: '/project/list',
        component: 'view.project_list',
        meta: {
          title: 'project_list',
          i18nKey: 'route.project_list',
          icon: 'ph:list-bullets',
          permissions: ['project.list.view']
        }
      },
      {
        name: 'project_order',
        path: '/project/order',
        component: 'view.project_order',
        meta: {
          title: 'project_order',
          i18nKey: 'route.project_order',
          icon: 'ph:receipt',
          permissions: ['project.order.view']
        }
      }
    ]
  },
  {
    name: 'quick-process',
    path: '/quick-process',
    component: 'layout.base$view.quick-process',
    meta: {
      title: 'quick-process',
      i18nKey: 'route.quick-process',
      icon: 'ph:lightning',
      order: 20
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'ph:gear-six',
      order: 100
    },
    children: [
      {
        name: 'system_admin-user',
        path: '/system/admin-user',
        component: 'view.system_admin-user',
        meta: {
          title: 'system_admin-user',
          i18nKey: 'route.system_admin-user',
          icon: 'ph:user-gear',
          permissions: ['system.admin-user.view']
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config',
          icon: 'ph:wrench',
          permissions: ['system.config.view']
        }
      },
      {
        name: 'system_log',
        path: '/system/log',
        component: 'view.system_log',
        meta: {
          title: 'system_log',
          i18nKey: 'route.system_log',
          icon: 'ph:clipboard-text',
          permissions: ['system.log.view']
        }
      },
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          title: 'system_permission',
          i18nKey: 'route.system_permission',
          icon: 'ph:lock-key',
          permissions: ['system.permission.view']
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'ph:shield-star',
          permissions: ['system.role.view']
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'ph:users-three',
      order: 40
    },
    children: [
      {
        name: 'user_checkin',
        path: '/user/checkin',
        component: 'view.user_checkin',
        meta: {
          title: 'user_checkin',
          i18nKey: 'route.user_checkin',
          icon: 'ph:calendar-check',
          permissions: ['user.checkin.view']
        }
      },
      {
        name: 'user_checkin-log',
        path: '/user/checkin-log',
        component: 'view.user_checkin-log',
        meta: {
          title: 'user_checkin-log',
          i18nKey: 'route.user_checkin-log',
          icon: 'ph:scroll',
          permissions: ['user.checkin-log.view']
        }
      },
      {
        name: 'user_kyc',
        path: '/user/kyc',
        component: 'view.user_kyc',
        meta: {
          title: 'user_kyc',
          i18nKey: 'route.user_kyc',
          icon: 'ph:identification-card',
          permissions: ['user.kyc.view']
        }
      },
      {
        name: 'user_level',
        path: '/user/level',
        component: 'view.user_level',
        meta: {
          title: 'user_level',
          i18nKey: 'route.user_level',
          icon: 'ph:crown',
          permissions: ['user.level.view']
        }
      },
      {
        name: 'user_login-log',
        path: '/user/login-log',
        component: 'view.user_login-log',
        meta: {
          title: 'user_login-log',
          i18nKey: 'route.user_login-log',
          icon: 'ph:clock-counter-clockwise',
          permissions: ['user.login-log.view']
        }
      },
      {
        name: 'user_member',
        path: '/user/member',
        component: 'view.user_member',
        meta: {
          title: 'user_member',
          i18nKey: 'route.user_member',
          icon: 'ph:user-list',
          permissions: ['user.member.view']
        }
      },
      {
        name: 'user_online',
        path: '/user/online',
        component: 'view.user_online',
        meta: {
          title: 'user_online',
          i18nKey: 'route.user_online',
          icon: 'ph:wifi-high',
          permissions: ['user.online.view']
        }
      },
      {
        name: 'user_relation',
        path: '/user/relation',
        component: 'view.user_relation',
        meta: {
          title: 'user_relation',
          i18nKey: 'route.user_relation',
          icon: 'ph:tree-structure',
          permissions: ['user.relation.view']
        }
      },
      {
        name: 'user_wallet',
        path: '/user/wallet',
        component: 'view.user_wallet',
        meta: {
          title: 'user_wallet',
          i18nKey: 'route.user_wallet',
          icon: 'ph:wallet',
          permissions: ['user.wallet.view']
        }
      }
    ]
  }
];
