/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "activity": "/activity";
    "agent": "/agent";
    "agent_report": "/agent/report";
    "agent_role": "/agent/role";
    "agent_user": "/agent/user";
    "content": "/content";
    "content_about": "/content/about";
    "content_marquee": "/content/marquee";
    "content_message": "/content/message";
    "content_news": "/content/news";
    "content_popup": "/content/popup";
    "finance": "/finance";
    "finance_recharge-audit": "/finance/recharge-audit";
    "finance_recharge-history": "/finance/recharge-history";
    "finance_spin-record": "/finance/spin-record";
    "finance_transaction-log": "/finance/transaction-log";
    "finance_withdraw-audit": "/finance/withdraw-audit";
    "finance_withdraw-history": "/finance/withdraw-history";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "mall": "/mall";
    "mall_category": "/mall/category";
    "mall_goods": "/mall/goods";
    "mall_shipping": "/mall/shipping";
    "project": "/project";
    "project_balance": "/project/balance";
    "project_balance-order": "/project/balance-order";
    "project_category": "/project/category";
    "project_guarantor": "/project/guarantor";
    "project_list": "/project/list";
    "project_order": "/project/order";
    "quick-process": "/quick-process";
    "system": "/system";
    "system_admin-user": "/system/admin-user";
    "system_config": "/system/config";
    "system_log": "/system/log";
    "system_permission": "/system/permission";
    "system_role": "/system/role";
    "user": "/user";
    "user_checkin": "/user/checkin";
    "user_checkin-log": "/user/checkin-log";
    "user_kyc": "/user/kyc";
    "user_level": "/user/level";
    "user_login-log": "/user/login-log";
    "user_member": "/user/member";
    "user_online": "/user/online";
    "user_relation": "/user/relation";
    "user_wallet": "/user/wallet";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "activity"
    | "agent"
    | "content"
    | "finance"
    | "home"
    | "iframe-page"
    | "login"
    | "mall"
    | "project"
    | "quick-process"
    | "system"
    | "user"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "activity"
    | "agent_report"
    | "agent_role"
    | "agent_user"
    | "content_about"
    | "content_marquee"
    | "content_message"
    | "content_news"
    | "content_popup"
    | "finance_recharge-audit"
    | "finance_recharge-history"
    | "finance_spin-record"
    | "finance_transaction-log"
    | "finance_withdraw-audit"
    | "finance_withdraw-history"
    | "home"
    | "mall_category"
    | "mall_goods"
    | "mall_shipping"
    | "project_balance-order"
    | "project_balance"
    | "project_category"
    | "project_guarantor"
    | "project_list"
    | "project_order"
    | "quick-process"
    | "system_admin-user"
    | "system_config"
    | "system_log"
    | "system_permission"
    | "system_role"
    | "user_checkin-log"
    | "user_checkin"
    | "user_kyc"
    | "user_level"
    | "user_login-log"
    | "user_member"
    | "user_online"
    | "user_relation"
    | "user_wallet"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
